title: MinteCalc Legal
description: Official legal documents for the MinteCalc mobile application
theme: jekyll-theme-minimal

# Custom domain
url: "https://legal.mintecalc.com"

# GitHub Pages settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
